# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/clk_vip_0/clk_vip_0.xci
# IP: The module: 'clk_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/clk_vip_0/clk_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vip_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/clk_vip_0/clk_vip_0.xci
# IP: The module: 'clk_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/clk_vip_0/clk_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
