# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/rgb2stream_0/rgb2stream_0.xci
# IP: The module: 'rgb2stream_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/rgb2stream_0/src/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/rgb2stream_0/src/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/rgb2stream_0/rgb2stream_0.xci
# IP: The module: 'rgb2stream_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/rgb2stream_0/src/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/rgb2stream_0/src/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
