# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7s15ftgb196-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir E:/Vivado/JQSJ_1/JQSJ.cache/wt [current_project]
  set_property parent.project_path E:/Vivado/JQSJ_1/JQSJ.xpr [current_project]
  set_property ip_repo_paths {
  e:/Vivado/RGB2DVI_IP
  e:/Vivado/SEA-master/Examples/FPGA-IP/IIC-IP/IP
  e:/Vivado/SEA-master/Examples/FPGA-IP/Camera-IP/IP/OV5647_Init_IP
  e:/Vivado/Camera_Demo/IP_Core/CSI2AXIS_1.0_IP
  e:/Vivado/Camera_Demo/IP_Core/CSI2DPHY_RX_1.0_IP
  e:/Vivado/Camera_Demo/Camera_Demo.srcs/sources_1/ip/clk_wiz_1
  e:/Vivado/FPGA_IP
  e:/Vivado/Camera_Demo
  e:/Vivado/JQSJ_1
  E:/Vivado/IP_Core
} [current_project]
  update_ip_catalog
  set_property ip_output_repo E:/Vivado/JQSJ_1/JQSJ.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet E:/Vivado/JQSJ_1/JQSJ.runs/synth_1/Driver_IIC_2.dcp
  read_ip -quiet e:/Vivado/JQSJ_1/JQSJ.srcs/sources_1/ip/Driver_IIC_2/Driver_IIC_2.xci
  link_design -top Driver_IIC_2 -part xc7s15ftgb196-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force Driver_IIC_2_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file Driver_IIC_2_drc_opted.rpt -pb Driver_IIC_2_drc_opted.pb -rpx Driver_IIC_2_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force Driver_IIC_2_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file Driver_IIC_2_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file Driver_IIC_2_utilization_placed.rpt -pb Driver_IIC_2_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file Driver_IIC_2_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force Driver_IIC_2_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file Driver_IIC_2_drc_routed.rpt -pb Driver_IIC_2_drc_routed.pb -rpx Driver_IIC_2_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file Driver_IIC_2_methodology_drc_routed.rpt -pb Driver_IIC_2_methodology_drc_routed.pb -rpx Driver_IIC_2_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file Driver_IIC_2_power_routed.rpt -pb Driver_IIC_2_power_summary_routed.pb -rpx Driver_IIC_2_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file Driver_IIC_2_route_status.rpt -pb Driver_IIC_2_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file Driver_IIC_2_timing_summary_routed.rpt -pb Driver_IIC_2_timing_summary_routed.pb -rpx Driver_IIC_2_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file Driver_IIC_2_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file Driver_IIC_2_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file Driver_IIC_2_bus_skew_routed.rpt -pb Driver_IIC_2_bus_skew_routed.pb -rpx Driver_IIC_2_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force Driver_IIC_2_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

